version: '3.7'
services:
  flask-crud:
    container_name: flask-crud
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    ports:
      - 9100:5000
    volumes:
      - ./src/:/app
    depends_on:
      - mysql
      
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '33067:3306'
    volumes:
      - .mysql_dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'admin'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'flask'
      MYSQL_ROOT_PASSWORD: 'root'

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8081:8080
    depends_on:
      - mysql